// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260707101917_lots_tags_to_tag")]
    partial class lots_tags_to_tag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("current_price")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("end_time")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("initial_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("tag_id")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("tagid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userlogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("tagid");

                    b.HasIndex("userlogin");

                    b.ToTable("lots");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("login");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("App.Models.Lot", b =>
                {
                    b.HasOne("App.Models.Tag", "tag")
                        .WithMany("lots")
                        .HasForeignKey("tagid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.User", "user")
                        .WithMany("lots")
                        .HasForeignKey("userlogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tag");

                    b.Navigation("user");
                });

            modelBuilder.Entity("App.Models.Tag", b =>
                {
                    b.Navigation("lots");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Navigation("lots");
                });
#pragma warning restore 612, 618
        }
    }
}
